### ISSUE TITLE
Getting certificate error issue when connecting  OUD from OUDSM in Kubernetes

### ISSUE THREAD

**Issue by veerareddyakkili** [oehrlis/oudbase#52]
Hi,

Deployed OUD and OUDSM in 2 different nodes and trying to access OUD through OUDSM and getting below error.

**There is an error with the certificate presented by the server oudself4444.px-npe1101.pks.XXXX.com:30007. Details: java.security.cert.CertificateException: No name matching oudself4444.px-npe1101.pks.XXXX.com found**

I have created self-signed certificates with  multiple domains and added to jKS in OUD and OUDSM but OUD is not referring to certificates from JAVA CaCerts and its creating its own selfsigned certificate and causing this problem.

**Comment by oehrlis** [comment]
Hi Sorry, I did never answer your Issue.

The problem is related to java security enhancements where endpoint identification has been enabled. See MOS Note [2470313.1](https://support.oracle.com/epmos/faces/DocumentDisplay?id=2470313.1) and MOS Note [2463219.1](https://support.oracle.com/epmos/faces/DocumentDisplay?id=2463219.1) as well blog post [Oracle Unified Directory SSLHandshakeException with Java 1.8.0_181
](https://www.oradba.ch/2018/08/oracle-unified-directory-sslhandshakeexception-with-java-1-8-0_181/)

Cheers
Stefan
