### ISSUE TITLE
oracle-odsee

### ISSUE THREAD

**Issue by josecoelho** [oehrlis/oudbase#66]
We have a legacy project to search and edit an LDAP ODSEE.

I'm trying to set up this on docker to make development and tests easier. I just built an image with success based on the archived project https://github.com/oehrlis/docker-odsee. 

I had to update paths and links related to the new release of [`oudbase`](https://github.com/oehrlis/oudbase). I'm not sure why your project is archived, but I believe this might be useful for other developers dealing with legacy. Was this project moved to another place? I believe the expected place would be https://github.com/oracle/docker-images. I'm not sure.

Should I fork and keep the updates on my fork, or should I contribute somewhere else?
This is the PR related to the fixes. https://github.com/josecoelho/docker-odsee/pull/1

**Comment by oehrlis** [comment]
Hi

A couple of month ago I did consolidate my docker build scripts for Oracle Databases, Oracle Unified Directory, ODSEE etc into one repository https://github.com/oehrlis/docker You find the latest ODSEE build script there. Thats the reason why I did archived project https://github.com/oehrlis/docker-odsee The build scripts and dockerfiles have been consolidated and improved e.g. multistage builds, simplified to add patches etc.

The other directory you did mentioned (https://github.com/oracle/docker-images) is the official Oracle Repository for their Docker Build scripts. There you can find a couple of build scripts for the latest Oracle products including Oracle Unified Directory (OUD). Although the OUD build scripts are maintained by me. They usually a bit behind the ones you find in my repo (https://github.com/oehrlis/docker) I do assume, that Oracle would not integrate ODSEE in its official repository, since OUDSEE is a legacy product.

I did approve you pull request to https://github.com/oehrlis/docker-odsee but haven't take the repo out of archive. You may use and contribute to https://github.com/oehrlis/docker

Just let me now if there are issues with oudbase related to ODSEE. Haven't used it for a while on ODSEE.

Regards
Stefan

**Comment by oehrlis** [comment]
Hi Jose

I've just added a Note to the readme in https://github.com/oehrlis/docker-odsee

If you run into issues with the ODSEE just open an issue on the new repo. Haven't used ODSEE for a while.

Regards
Stefan

**Comment by oehrlis** [comment]
Hi Jose

As this issue is related to ODSEE docker container I'll close it her. Please use https://github.com/oehrlis/docker to create an issue related to the docker build scripts.

Regards
Stefan
